---

- name: create schematics actions
  hosts: localhost
  gather_facts: true
  collections:
    - community.general

  vars:
    json_data: "{{ lookup('file','adata.json') | from_json }}"
    cleanconfig:    true
    workspacelist:  false
    manlookup:      false

  tasks:

    - name: Run ibmcloud cli
      shell: "ibmcloud schematics action list -j > adata.json"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )
      when: workspacelist | bool

    - name: Include vars 
      ansible.builtin.include_vars:
        file: action_setting.yml
        name: act

    - block:

       - name: Create template for action management
         include_tasks: act-management.yml

    - name: Remove config files (delete file)
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob: "*.json"
      when: cleanconfig | bool



