- name: Include vars
  ansible.builtin.include_vars:
    file: workspace_settings.yml
    name: ws

- name: Template files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
  loop:
    - { src: 'bmshost.js', dst: '{{ workspace_bms_name }}.json' }

- name: Run ibmcloud cli
  shell: "ibmcloud schematics workspace new -f {{ workspace_bms_name }}.json"
  register: ibmcli_output
  failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )

- name: Output of ibmcli command
  ansible.builtin.debug:
    msg: '{{ item }}'
  loop:
    - '{{ ibmcli_output }}'

