---

- name: create schematics workspace
  hosts: localhost
  gather_facts: true
  collections:
    - community.general

  tags:
    - bms

#  vars:
#    workspace_bms_name: "ci-bms-single-esxi"
#    repo_bms: "https://github.com/jimccann-rh/ibmc-workspace-bms-single-quote.git"

  vars:
    json_data: "{{ lookup('file','data.json') | from_json }}"

  tasks:

    - name: Run ibmcloud cli
      shell: "ibmcloud schematics workspace list -j > data.json"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )

    - name: Include vars 
      ansible.builtin.include_vars:
        file: workspace_settings.yml
        name: ws

    - block:

#E       - name: Create templates for twingate
#E         include_tasks: twingate.yml
#E
#E       - name: Create templates for BMS esxi
#E         include_tasks: bms.yml
#E         loop: "{{ range( ws.name_bms_start, ws.name_bms_count + 1 )|list }}"
#E         loop_control:
#E           loop_var: loop_bms
#E           index_var: my_idx

