---

- name: create schematics workspace
  hosts: localhost
  gather_facts: true
  collections:
    - community.general

  tags:
    - bms

#  vars:
#    workspace_bms_name: "ci-bms-single-esxi"
#    repo_bms: "https://github.com/jimccann-rh/ibmc-workspace-bms-single-quote.git"



  tasks:

    - name: Include vars 
      ansible.builtin.include_vars:
        file: workspace_settings.yml
        name: ws

    - block:

       - name: Create custom media and mount media
         include_tasks: bms.yml
         loop: "{{ range(0, 4 + 1)|list }}"
         loop_control:
#           loop_var: loop_bms
           index_var: my_idx



#    - name: Include vars 
#      ansible.builtin.include_vars:
#        file: workspace_settings.yml
#        name: ws
#
#    - name: Template files
#      ansible.builtin.template:
#        src: '{{ item.src }}'
#        dest: '{{ item.dst }}'
#      loop:
#        - { src: 'bmshost.js', dst: '{{ workspace_name }}.json' }
#
#    - name: Run ibmcloud cli
#      shell: "ibmcloud schematics workspace new -f {{ workspace_name }}.json"
#      register: ibmcli_output
#      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )
#    
#    - name: Output of ibmcli command
#      ansible.builtin.debug:
#        msg: '{{ item }}'
#      loop:
#        - '{{ ibmcli_output }}'




