---

- name: create schematics workspaces
  hosts: localhost
  gather_facts: true
  collections:
    - community.general

  vars:
    json_data: "{{ lookup('file','data.json') | from_json }}"
    workspacelist: false
    twingatelookup: false 
    bmslookup: false
    manlookup: false

  tasks:

    - name: Run ibmcloud cli
      shell: "ibmcloud schematics workspace list -j > data.json"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )
      when: workspacelist | bool

    - name: Include vars 
      ansible.builtin.include_vars:
        file: workspace_settings.yml
        name: ws

    - block:

       - name: Create template for twingate
         include_tasks: twingate.yml


    - block:

       - name: Create template for management
         include_tasks: management.yml


    - block:

       - name: Create templates for BMS esxi
         include_tasks: bms.yml
         loop: "{{ range( ws.name_bms_start, ws.name_bms_count + 1 )|list }}"
         loop_control:
           loop_var: loop_bms
           index_var: my_idx

