- name: set fact
  set_fact:
    twingatelookup: "{{ item.name in ws.name_workspace_twingate_name }}"
  loop: "{{ json_data.workspaces }}"

- name: data
  debug:
    var: twingatelookup

- name: data workspace
  debug:
    msg: "{{ item.name }}"
  loop: "{{ json_data.workspaces }}"

- name: data 
  debug:
    msg: "{{ ws.name_workspace_twingate_name }}"


- block:

    - name: Template files
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ item.dst }}'
      loop:
        - { src: 'twingate.js', dst: '{{ ws.name_workspace_twingate_name }}.json' }
    
    - name: Run ibmcloud cli
      shell: "#ibmcloud schematics workspace new -f {{ ws.name_workspace_twingate_name }}.json"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )
    
    - name: Output of ibmcli command
      ansible.builtin.debug:
        msg: '{{ item }}'
      loop:
        - '{{ ibmcli_output }}'
  when: twingatelookup | bool
