- block:

    - name: Template files
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ item.dst }}'
      loop:
        - { src: 'vlans.js', dst: '{{ ws.name_workspace_vlans_name }}.json' }
    
    - name: Run ibmcloud cli
      shell: "ibmcloud schematics workspace new -f {{ ws.name_workspace_vlans_name }}.json"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )
    
    - name: Output of ibmcli command
      ansible.builtin.debug:
        msg: '{{ item }}'
      loop:
        - '{{ ibmcli_output }}'
  when: vlanslookup | bool
